### ISSUE TITLE
media_baseurl is always prepended to screenshots urls

### ISSUE THREAD

**Issue by minlexx** [ximion/appstream#395] opened 2022-04-16 12:26 UTC
Symptom: screenshot URLs look like this (note double `https://`) _(sreenshot from debugger session)_
![image](https://user-images.githubusercontent.com/13084776/163674179-73c6fda8-af58-4857-89b7-55bc6cfbe6b3.png)

As we can see in [src/as-image.c#L342](https://github.com/ximion/appstream/blob/d542f5806172649e530546606689e16f41f049df/src/as-image.c#L342) base url is appended unconditinally, resulting in screenshot image that cannot be downloaded and degraded user experience in software center application (plasma-discover in our case).

Metadata XML fragment for this looks like:
```
<screenshot type="default">
      <image type="source">https://cdn.kde.org/screenshots/ktorrent/ktorrent.png</image>
      <image type="source" width="766" height="541">org/kde/ktorrent.desktop/214435abe2b8d85089dc352adbfb4873/screenshots/image-1_orig.png</image>
      <image type="thumbnail" width="752" height="531">org/kde/ktorrent.desktop/214435abe2b8d85089dc352adbfb4873/screenshots/image-1_752x531.png</image>
      <image type="thumbnail" width="624" height="440">org/kde/ktorrent.desktop/214435abe2b8d85089dc352adbfb4873/screenshots/image-1_624x440.png</image>
      <image type="thumbnail" width="224" height="158">org/kde/ktorrent.desktop/214435abe2b8d85089dc352adbfb4873/screenshots/image-1_224x158.png</image>
</screenshot>
```

The issue can be reproduced by small example program that loads single metadata file:
 * source file: [minlexx/test_appstream_screenshots](https://github.com/minlexx/test_appstream_screenshots/blob/main/main.cpp)
 * metadata file with a single component [Components-x86_64.xml
](https://github.com/minlexx/test_appstream_screenshots/blob/main/metadta/Components-x86_64.xml) taken from real data
 * example output:
```
test: Pool default flags:  "FlagLoadOsCollection | FlagLoadOsMetainfo | FlagLoadFlatpak"
test: Pool new flags:  "FlagLoadOsCollection"
test: Adding extra metadata path:  "/home/lexx/dev/test/build-test_appstream-System_Qt-Debug/metadata"
test: Loaded total  1  components
test: Found ktorrent  1  times
test:    "org.kde.ktorrent.desktop"
test:      "KindSource" ; url:  "https://appstream.alpinelinux.org/media/edge/https://cdn.kde.org/screenshots/ktorrent/ktorrent.png"
test:      "KindSource" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_orig.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_752x531.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_624x440.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_224x158.png"
```

As you can see also from test example, first screenshot URL has extra `https://` added.

Suggested fix is by checking for absolute URL with g_str_has_prefix (or whatever the correct way in glib is, I'm Qt user, don't know much about glib). In case if screenshot URL is already starting with `https://`, do not append media_baseurl.

P.S. downstream issue for reference: https://gitlab.alpinelinux.org/alpine/infra/compose/appstream-generator/-/issues/2

**Comment by minlexx** [comment] 2022-04-16 12:52
I have a dumb fix that works, but I'm not sure this is absolutely correct way to handle this situation

```diff
diff --git a/src/as-image.c b/src/as-image.c
index 012d243b..ee9fe9db 100644
--- a/src/as-image.c
+++ b/src/as-image.c
@@ -266,6 +266,11 @@ as_image_set_locale (AsImage *image, const gchar *locale)
        as_ref_string_assign_safe (&priv->locale, locale);
 }
 
+static gboolean is_url_absolute (const gchar *url)
+{
+       return g_str_has_prefix (url, "https://") || g_str_has_prefix (url, "http://");
+}
+
 /**
  * as_image_load_from_xml:
  * @image: a #AsImage instance.
@@ -333,8 +338,8 @@ as_image_load_from_xml (AsImage *image, AsContext *ctx, xmlNode *node, GError **
        }
 
        g_strstrip (content);
-       if (!as_context_has_media_baseurl (ctx)) {
-               /* no baseurl, we can just set the value as URL */
+       if (!as_context_has_media_baseurl (ctx) || is_url_absolute (content)) {
+               /* no baseurl or URL is already absolute path, we can just set the value as URL */
                as_image_set_url (image, content);
        } else {
                /* handle the media baseurl */
```

After applying this I see correct output from my test program

```
test: Pool default flags:  "FlagLoadOsCollection | FlagLoadOsMetainfo | FlagLoadFlatpak"
test: Pool new flags:  "FlagLoadOsCollection"
test: Adding extra metadata path:  "/home/lexx/dev/test/build-test_appstream-System_Qt-Debug/metadata"
test: Loaded total  1  components
test: Found ktorrent  1  times
test:    "org.kde.ktorrent.desktop"
test:      "KindSource" ; url:  "https://cdn.kde.org/screenshots/ktorrent/ktorrent.png"
test:      "KindSource" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_orig.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_752x531.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_624x440.png"
test:      "KindThumbnail" ; url:  "https://appstream.alpinelinux.org/media/edge/org/kde/ktorrent.desktop/2250ef363428df697ba6e87d1d66e821/screenshots/image-1_224x158.png"
```

P.S need to not forget to remove `~/.cache/appstream` to see the effect

**Comment by ximion** [comment] 2022-04-16 22:18
The AppStream behavior is actually correct: If there is a media baseurl, it must be prepended to every media URL segment in a metadata file (great performance improvement when processing thousands of components).
The real bug here is the `<image type="source">https://cdn.kde.org/screenshots/ktorrent/ktorrent.png</image>` entry in a file that has a media_baseurl set - that entry should not be there, so unless it was inserted by other means, there is a bug in the code that generated this file, most likely libappstream-compose or appstream-generator.

**Comment by minlexx** [comment] 2022-04-17 13:27
The data is taken without modifications from what was generated by appstream-generator (with alpinelinux backend).

**Comment by ximion** [comment] 2022-04-17 18:34
Yeah, that's wrong, there is a bug somewhere. What is your settings file for asgen that you used to generate this data?

**Comment by minlexx** [comment] 2022-04-18 10:17
It's generated on Alpine infra, using this I believe https://gitlab.alpinelinux.org/alpine/infra/compose/appstream-generator/-/blob/master/asgen-config.json

**Comment by ximion** [comment] 2022-04-21 00:55
I had a look at this, but still don't know how this could happen - the code shouldn't be able to take a branch where the media_baseurl is set *and* source image URLs from screenshots are taken without using the media_baseurl *and* the media_baseurl is correctly used for any generated thumbnails.
I also couldn't reproduce this yet, but I'll keep trying. Odd question, just on the offchance that you hit an old bug: Can you make sure the generator reprocesses the ktorrent package and doesn't just return cached data? Something like `appstream-generator forget ktorrent` (followed by a `process --force`) should do the trick!
I don't think this will change anything though, because I am not aware that any such bug happened and was fixed in the past... But output like this should definitely not have been generated.

**Comment by minlexx** [comment] 2022-04-21 11:18
Thank you for looking into this!

I'll try to run generator locally, but I haven't tried it yet myself and I'm afraid it will take some time.

P.S. ktorrent is not the only package with this issue, many org.kde.* packages I looked at had similar screenshot URLs

**Comment by pabloyoyoista** [comment] 2022-04-21 12:59
> Which version of AppStream and which version of appstream-generator are you using?

I can confirm that this is happening with appstream-generator=0.8.8 and appstream=0.15.3. I "forgot" d-feet package in main, regenerated, and the issue is still there: https://appstream.pcorreag.tk/data/edge/main/Components-x86_64.xml.gz

**Comment by ximion** [comment] 2022-04-21 13:38
> Would you like us to try with the latest master commit?

You can, but I don't think this will do anything - I just fixed another potential issue that nobody encountered yet that I found while reviewing the code.
Running `appstream-generator` with `--verbose` and attaching the log of a `run` run may give a clue though!

**Comment by pabloyoyoista** [comment] 2022-04-21 13:48
>  Running appstream-generator with --verbose and attaching the log of a run run may give a clue though!

Absolutely!  
[generator.log](https://github.com/ximion/appstream/files/8531508/tmp.log)

I modified the config Alexei pointed to. I kept only "main" section and "aarch64" and "x86_64" architectures to reduce cruft from the output.

**Comment by ximion** [comment] 2022-04-24 16:11
No matter what I try, I can't reproduce this issue at all...
I used this config file:
```json
{
"ProjectName": "AlpineLinux",
"ArchiveRoot": "http://dl-cdn.alpinelinux.org/alpine/",
"MediaBaseUrl": "https://appstream.alpinelinux.org/media",
"Backend": "alpinelinux",
"Suites":
  {
    "edge":
      {
        "sections": ["main"],
        "architectures": ["x86_64"]
      }
  },
  "Icons":
  {
    "48x48":   {"cached": false, "remote": true},
    "64x64":   {"cached": true, "remote": true},
    "128x128": {"cached": false, "remote": true}
  }
}
```
Using `AppStream Generator 0.8.9, AS: 0.15.4 [Alpine Linux]` on Debian as host.
I guess you are running this on Alpine, which uses musl(?) as libc, but that shouldn't actually cause any problems, especially not an odd one such as this one.
I guess you already did try removing database and cache entirely and trying this from scratch?

**Comment by ximion** [comment] 2022-04-24 16:39
You can try to take https://github.com/ximion/appstream-generator/commit/cc4df09f9dd110425b0cdb798956cfb1de42656c (fixes a few other issues), but I don't think this will do anything...
Maybe I do need an Alpine chroot to reproduce this issue...

**Comment by pabloyoyoista** [comment] 2022-04-25 19:33
@ximion, I have tried to reproduce your problems... And it is indeed a problem with alpine. Either muslc, some part of the D stack or something in between is messing up. The same configuration with 0.8.8+0.15.3 from debian sid and from alpine edge yield different results, running both from scratch and the same configuration file. The run on debian sid outputs the component file you expect, while the one in alpine edge outputs what we are reporting. I guess unless you feel like spending more time on this, we will have to report to alpine and see how can we solve it. Likely, this is also the reason for https://github.com/ximion/appstream-generator/issues/100

Thanks a lot for your time and your help! And sorry in the end the bug seems to be totally unrelated to the code you wrote, it feels like we are going to have a hard time figuring this one out :(

**Comment by ximion** [comment] 2022-04-25 20:56
@pabloyoyoista Don't worry :-) A bug is a bug. Which D compiler and which C compiler does Alpine use? This is an extremely odd bug...

**Comment by pabloyoyoista** [comment] 2022-04-25 21:45
> This is an extremely odd bug...

Yes, if at least it crashed...

> Which D compiler and which C compiler does Alpine use? 

We build `appstream-generator` with `ldc` because `gdc` failed the build. I saw similar issues in your CI, so I thought the compiler change was uncontroversial. From `appstream-generator` logs:
```
D compiler for the host machine: ldc2 (llvm 1.28.1 "LDC - the LLVM D compiler (1.28.1):")
D linker for the host machine: ldc2 ld.bfd 2.38
```

And from `ldc` logs:
```
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
....
-- Found host D compiler /usr/bin/gdmd, with default flags ''
-- Host D compiler ID: GDMD
-- Host D compiler version: gdc (Alpine 11.2.1_git20220117) 11.2.1 20220117
-- Host D compiler front-end version: 2076
-- LLVM_NATIVE_ARCH: AArch64
-- Found LLVM: /usr/lib/llvm12 (found suitable version "12.0.1", minimum required is "6.0") 
```
I understand these are actually the C and D default compilers.

Also, all of those link against `musl` :)

**Comment by ximion** [comment] 2022-04-25 22:11
If you also use GCC for the C code, then that's very uncontroversial, that would be what pretty much everyone uses - except for musl, of course.
I would expect a different libc to cause a wide variety of bugs, but not this one - the code that generates the AppStream XML output also is 100% C, so no D here.
Can you extract the d-feet archive into a directory and run something like `appstreamcli compose --media-baseurl='https://example.org' --media-dir=/tmp/ascmedia --result-root=/tmp/ascresult /path/to/extracted/data` and see what output you get in `/tmp/ascresult`?

**Comment by ximion** [comment] 2022-04-26 15:55
That's what I expected. Still not sure what the cause of this issue is, but this will simplify debugging greatly :-)

**Comment by pabloyoyoista** [comment] 2022-05-13 13:51
I've finally had the time and the energy to step by step dig into this with GDB, and it turns out the problem is not with musl, but with locales and maybe a bug in this project. What is currently happening in my alpine system with `LANG=C.UTF-8` in the environment. Note that the container in which we are running the generator is quite minimal and does not even have a locale setup, as far as I know. I will follow my example using the suggested `appstreamcli` command and `d-feet` as an example, which is downloadable [here](http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/d-feet-0.3.16-r1.apk) and extractable with `tar -xf d-feet-0.3.16-r1.apk`.

* First compose does the processing of the screenshots images in [asc_process_screenshot_images](https://github.com/ximion/appstream/blob/v0.15.3/compose/asc-utils-screenshots.c#L390):
  * Note, that the `AsScreenshot` already has one image coming from [its metainfo](https://gitlab.gnome.org/GNOME/d-feet/-/blob/master/data/org.gnome.dfeet.appdata.xml.in#L18).
  * That image is read and downloaded successfully to create the screenshot store and its correspondent local image is created and [inserted](https://github.com/ximion/appstream/blob/v0.15.3/compose/asc-utils-screenshots.c#L555) into the images. 
  * At this point, my intuition told me that there was something going wrong, since the previous original screenshot already existed in the list of images. However, an `as_screenshot_get_images(scr)` reported a `GPtrArray` of length one. Upon inspection of the `AsScreenshot`, I figured out that the original "remote" image, was only stored in `priv->images`, whereas the downloaded image existed both in  `priv->images` and `priv->images_lang`.
  * The function continues and generates all the thumbnails. At this stage, `priv->images_lang` returned by `as_screenshot_get_images(scr)` has 5 images, reportedly the correct ones, whereas `priv->images` returned by `as_screenshot_get_images_all(scr)` has 6 images, reportedly the problem we are seeing in this issue.
* After the processing, the screenshots do not seem to be modified, and one arrives at [as_screenshot_to_xml_node](https://github.com/ximion/appstream/blob/v0.15.3/src/as-screenshot.c#L571)
  * Such function iterates through `priv->images` [here](https://github.com/ximion/appstream/blob/v0.15.3/src/as-screenshot.c#L583-L584), giving out the 6 images we see in alpine.

A simple fix would be to use `as_screenshot_get_images` in `as_screenshot_to_xml_node`, but I am not sure which is the expected behavior or how the `images_lang` is supposed to work. @ximion, you say if this is the correct fix or there is something that we must change in the locales and retry. I have not tried to reproduce with my proposed fix, although the  GDB output is pretty clear at this point :)

```
Thread 1 "appstreamcli-co" hit Breakpoint 10, as_screenshot_to_xml_node (screenshot=0x7ffff6a32680 [AsScreenshot], ctx=ctx@entry=0x7ffff6d59500 [AsContext], root=root@entry=0x7ffff62fc690) at ../src/as-screenshot.c:573
573     ../src/as-screenshot.c: No such file or directory.
(gdb) n
56      in ../src/as-screenshot.c
(gdb) n
573     in ../src/as-screenshot.c
(gdb) n
576     in ../src/as-screenshot.c
(gdb) n
577     in ../src/as-screenshot.c
(gdb) p priv->images
$72 = (GPtrArray *) 0x7ffff6d59b80
(gdb) p *priv->images
$73 = {pdata = 0x7ffff5fa5a70, len = 6}
(gdb) p *priv->images_lang
$74 = {pdata = 0x7ffff5f6e0a0, len = 5}
```

**Comment by ximion** [comment] 2022-05-13 15:48
Oh no! Thank you for the debugging effort! This is a direct cause of the localized-screenshots support having been bolted on at a later stage, with older code now doing the wrong thing... On its own that would be a bug, but there also appears to be a second issue here with AppStream not considering the "C" locale compatible with "C.UTF-8" on Alpine in `as_utils_locale_is_compatible`.
Not sure what that is about yet, but the compose code needs to be made aware of localized screenshots. I will work on that next week (I can't squeeze this in right now...).

In the meanwhile, you could maybe try the patch above, which, if I understand the problem correctly, should at least prevent the bad data generation for now (fixing the root cause will take a bit more effort though).

**Comment by pabloyoyoista** [comment] 2022-05-13 16:26
That certainly looks like it will certainly fix the issue. I'll test it this weekend locally, and if it works, push the fix to alpine.

> there also appears to be a second issue here with AppStream not considering the "C" locale compatible with "C.UTF-8" on Alpine in as_utils_locale_is_compatible

Is this something you would need us to debug too? Some specific information on what is the expected behavior and what is that the localization is messing up?

**Comment by pabloyoyoista** [comment] 2022-05-13 16:26
And BTW, thanks a lot for the very fast fix!! :D

**Comment by pabloyoyoista** [comment] 2022-05-14 12:20
I can confirm the issue is gone locally!! Will proceed to push it to alpine and to test it in the generator container. Thank you very, very much for your help!!

**Comment by pabloyoyoista** [comment] 2022-05-19 10:05
I can confirm this is gone in the container after dropping the caches :) Feel free to close this if you consider it solved!

**Comment by minlexx** [comment] 2022-05-19 10:13
> I can confirm this is gone in the container after dropping the caches :) Feel free to close this if you consider it solved!

Is there a new data generated somewhere already, to test?

**Comment by pabloyoyoista** [comment] 2022-05-19 10:19
> Is there a new data generated somewhere already, to test?

The full run is in process. You'll find it updated in my testing machine in a couple of hours: https://appstream.pcorreag.tk/data/

**Comment by ximion** [comment] 2022-05-19 11:42
> I can confirm this is gone in the container after dropping the caches :) Feel free to close this if you consider it solved!

This needs two more things to be properly fixed :-) Not sure yet what the locale issue is in Alpine, but I'll add a unit test for that so we can investigate that further (and maybe doing so will also yield some insight already).
The localized screenshots stuff also needs to be implemented. All of this will for sure be in the next release.

**Comment by ximion** [comment] 2022-05-22 18:29
This should work now, but keep an eye out if localization of AppStream data works well on Alpine clients!
I am not 100% sure that that issue is fully addressed as well.

**Closed by ximion** 2022-05-22 18:29 UTC
Labels: compose

**Comment by pabloyoyoista** [comment] 2022-05-22 19:09
Wonderful, thank you very much! We'll see if we bump into more issues. But it looks like the code handles well the circumstance where there is not locale environment variable set. So it should be all fine :)
