### ISSUE TITLE
AppData Description gets rendered out of order

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#116] opened 2017-06-08 20:54 UTC
from https://github.com/elementary/appcenter/issues/333
The description of my app has a paragraph block followed by an unordered list, followed by another paragraph. The unordered list somehow gets rendered below the two paragraphs in AppCenter.

My description looks like this:

`  <description>
    <p>
      Agenda is a simple, slick, speedy and no-nonsense task manager. Use it to keep track of the tasks that matter most.
    </p>
    <ul>
      <li>Blazingly fast and light</li>
      <li>Remembers your list until you clear completed tasks</li>
      <li>Autocompletion for previously added tasks</li>
      <li>Quit with the Esc key</li>
    </ul>
    <p>
      I dare you to find an easier, faster, more beautiful task manager for elementary OS.
    </p>
  </description>`

AppCenter looks like this:

![appcenterissue](https://user-images.githubusercontent.com/2007067/26949862-386f257e-4c61-11e7-9bc0-43aec0ae035b.png)

**Comment by hughsie** [comment] 2017-06-08 20:59
Looks like valid markup to me. I assume appstream-glib does the right thing?

**Comment by ximion** [comment] 2017-06-08 21:36
I guess this is because of the "release descriptions can start with an enumeration" patch that was recently applied to your packaging.

I need to rewrite that particular code anyway, so consider this fixed for the next release (which is where the patch that broke it is from anyway ^^).
The markup is completely fine, no issues there - it's just the parser that is a bit dumb in current Git master.

**Comment by ximion** [comment] 2017-07-01 22:35
Okay, I tried multiple things now, I even added a new testcase dedicated to this bug, but I could not reproduce this. The XML is always parsed correctly in any form, the YAML output matches the expectations as well, and I see no other way this could possibly fail.

The only possibility remaining is that the appstream-generator interferes (unlikely, it doesn't touch the description when the metainfo file defines one) or that the patch you applied to AppStream in Elementary to fix the "description can't start with enumeration" bug somehow doesn't work as expected on the older AppStream version.

**Comment by ximion** [comment] 2017-07-01 22:46
It's also not a bug in the built-in simple markup rendering function.
So yeah, this is either an issue in AppCenter, appstream-generator or in their interplay with libappstream.

Can you maybe update both appstream-generator and AppStream on your server to the newest version, and then tell it to re-scan the affected package?

**Comment by ximion** [comment] 2017-08-30 19:13
I'm closing this, because I can still not reproduce it. Please reopen this report, in case the bug is still happening.

**Closed by ximion** 2017-08-30 19:13 UTC
Labels: incomplete

**Comment by cassidyjames** [comment] 2018-02-07 22:42
I just had this happen with an app in elementary OS as well. Not sure where exactly the issue is, but I was pointed here.

My AppStream description is:
https://github.com/cassidyjames/dippi/blob/b27291377cc0c9350f28b5a00c3bf8885dafffd2/data/com.github.cassidyjames.dippi.appdata.xml.in#L9-L35

On my machine, however, dumping the appstream data gives me
```xml
<description>
  <p xml:lang="en_US">Analyze any display. Input a few simple details and figure out the aspect ratio, DPI, and other details of a particular display. Great for deciding which laptop or external monitor to purchase, and if it would be considered HiDPI.</p>
  <p xml:lang="en_US">Handy features:</p>
  <p xml:lang="en_US">Based on the expertise of Cassidy James Blaede and the actual logic System76 uses to determine screen size and resolution combinations.</p>
  <p xml:lang="en_US">Tells you if a display‘s density is:</p>
  <p xml:lang="en_US">Special thanks:</p>
  <ul>
    <li xml:lang="en_US">Find out if a display is a good choice based on its size and resolution</li>
    <li xml:lang="en_US">Get advice about different densities</li>
    <li xml:lang="en_US">Differentiates between laptops and desktop displays</li>
    <li xml:lang="en_US">Stupid simple: all in a cute li'l window</li>
  </ul>
  <ul>
    <li xml:lang="en_US">Very Low DPI,</li>
    <li xml:lang="en_US">Fairly Low DPI,</li>
    <li xml:lang="en_US">Ideal for LoDPI,</li>
    <li xml:lang="en_US">Potentially Problematic,</li>
    <li xml:lang="en_US">Ideal for HiDPI,</li>
    <li xml:lang="en_US">Fairly High for HiDPI, or</li>
    <li xml:lang="en_US">Too High DPI</li>
  </ul>
  <ul>
    <li xml:lang="en_US">Micah Ilbery for the shiny icons!</li>
    <li xml:lang="en_US">Daniel Foré for his apps to use as code examples</li>
    <li xml:lang="en_US">David Jordan for helping determine DPI ranges</li>
  </ul>
</description>
```

The XML is validated with `appstreamcli validate` at build time and passes.

**Comment by ximion** [comment] 2018-02-08 03:27
Which version of AppStream do you have? (`appstreamcli --version`)

**Comment by cassidyjames** [comment] 2018-02-08 03:30
I'm not sure what the version on the server is, but it turns out this was an issue with a related parsing process in [Houston](https://github.com/elementary/houston) that has been fixed. Sorry for the bother!
