### ISSUE TITLE
Build fail with 0.16.2 on Windows(MSYS2)

### ISSUE THREAD

**Issue by taozuhong** [ximion/appstream#499] opened 2023-06-05 02:37 UTC
The output message as follow:
```
Found pkg-config: C:\msys\ucrt64\bin/pkg-config.EXE (1.8.0)
Run-time dependency glib-2.0 found: YES 2.76.3
Run-time dependency gobject-2.0 found: YES 2.76.3
Run-time dependency gio-2.0 found: YES 2.76.3
Found CMake: C:\msys\ucrt64\bin/cmake.EXE (3.25.2)
Run-time dependency gio-unix-2.0 found: NO (tried pkgconfig and cmake)

../appstream-0.16.2/meson.build:156:15: ERROR: Dependency "gio-unix-2.0" not found, tried pkgconfig
and cmake

A full log can be found at D:/Codelabs/GitHub/msys/src/build-UCRT64/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambigu
ous and deprecated.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by ximion** [comment] 2023-06-05 11:26
Duplicate of https://github.com/ximion/appstream/issues/231 - patches for Windows support are welcomed, but unfortunately I don't have the bandwidth (or the Windows license) to work on this myself.
It's odd that `gio-unix-2.0` is unavailable on MSYS2 though, I would assume it provides a wrapper for it somehow...

**Closed by ximion** 2023-06-05 11:26 UTC
Labels: duplicate, help wanted
