### ISSUE TITLE
Mention how to define proprietary license

### ISSUE THREAD

**Issue by tintou** [ximion/appstream#233] opened 2019-05-14 09:50 UTC
It seems that the way forward is to use `<project_license>LicenseRef-proprietary</project_license>` (looking at libappstream-glib) but the documentation doesn't mention it anywhere

**Comment by hughsie** [comment] 2019-05-14 10:04
I think @ximion wasa against this before, but I do think it would be a handy note to have in the spec.

**Comment by cassidyjames** [comment] 2019-05-14 17:54
This is also implemented in at least [GNOME Software](https://gitlab.gnome.org/GNOME/gnome-software/blob/master/lib/gs-app.c#L2305), [AppCenter](https://github.com/elementary/appcenter/blob/37ac146a28572690025d73e9a50339b889d579f3/src/Views/AppInfoView.vala#L273), and the AppCenter fork of Pop!_Shop, plus what [several](https://github.com/flathub/com.dropbox.Client/blob/1da37e6df00f0701d7995f6f22e29910a40a298f/com.dropbox.Client.appdata.xml#L5) [apps](https://github.com/flathub/com.visualstudio.code/blob/6d8009ef2bc2df4f07b6ce466e4b717adb187da7/com.visualstudio.code.appdata.xml#L5) [in](https://github.com/flathub/com.valvesoftware.Steam/blob/96fd4610c22154091905881ac1cdd1f5d5f2da08/com.valvesoftware.Steam.appdata.xml#L25) [Flathub](https://github.com/flathub/com.mojang.Minecraft/blob/112db80afb02cf6eaa116c519c9b60ddd38886eb/com.mojang.Minecraft.appdata.xml#L51)—plus the [Flathub website](https://github.com/flathub/linux-store-backend/blob/109c3b48cfe329427463e02500e3348b3ca9275e/src/main/java/org/flathub/api/service/SyndicationServiceImpl.java#L104) itself—are using. So it seems pretty defacto across implementations.

**Comment by ximion** [comment] 2019-05-16 21:27
@hughsie If I was against this, I don't remember it ^^ - especially since it's the way SPDX wants us to do these things and the spec already includes it in an example for driver components: https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Driver.html
So, if you have a PR for this I will happily merge it (otherwise I'll just add at the next bug squashing day for this project)

**Comment by ximion** [comment] 2019-06-16 02:27
Duplicate of https://github.com/ximion/appstream/issues/107

**Closed by ximion** 2019-06-16 02:27 UTC
Labels: duplicate
