### ISSUE TITLE
Add pixel density descriptors to images

### ISSUE THREAD

**Issue by sophie-h** [ximion/appstream#355] opened 2021-09-10 23:22 UTC
I already had the problem that apps with small windows did supply HighDPI screenshots. That resulted in the screenshots being shown with a larger-than-reality size which I want to avoid. I don't think enforcing one specific scaling factor is a scalable (sorry) solution.

I think that something like a "pixel density descriptor" as in HTML (e.g. `scale="1.5"`) would be a good solution. Not necessarily to supply multiple scaling but just to get the output of the image right.

This would probably apply to videos as well but not sure.

**Comment by ximion** [comment] 2021-09-11 22:11
Duplicate of https://github.com/ximion/appstream/issues/114, but I think it's time to address this :-)

**Closed by ximion** 2021-09-11 22:11 UTC
Labels: duplicate
